---
name: packer-build

on:
  push:
    branches:
      - gha

concurrency:
  group: packer
  cancel-in-progress: false

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
  BOX_ORG: ${{ github.repository_owner }}

jobs:
  packer:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packer validate
        run: make validate

      - name: Packer build
        run: make build
