---
name: packer-release

on:
  push:
    tags:
      - v*

concurrency:
  group: packer
  cancel-in-progress: false

jobs:
  packer:
    runs-on: macos-12
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packer validate
        run: make validate

      - name: Packer build
        run: make build

      # - name: Create dummy box
      #   run: |
      #     mkfile 1b builds/st2_v-$(date +%Y%m%d).box

      - name: Create GH Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: true
          title: StackStorm Box ${{ github.ref_name }}
          files: |
            builds/st2_v-*.box
