---
name: packer-release

on:
  push:
    tags:
      - v*

concurrency:
  group: packer
  cancel-in-progress: true

jobs:
  packer:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Packer validate
      #   run: make validate

      # - name: Packer build
      #   run: make build

      - name: Create dummy box
        run: |
          touch builds/st2_v-$(date +%Y%m%d).box

      - name: Create GH Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: true
          title: Development Build
          files: |
            builds/st2_v-*.box
