---
name: packer-build

on:
  push:
    branches:
      - gha

concurrency:
  group: packer-build
  cancel-in-progress: false

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
  BOX_ORG: ${{ github.repository_owner }}

jobs:
  packer:
    runs-on: macos-12
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packer validate
        run: make validate

      - name: Packer build
        run: make build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: StackStorm Box ${{ github.run_number }}
          path: |
            builds/st2_*.box
          if-no-files-found: error
          retention-days: 1
